### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by anuragsachdeva28** [MMIL/MCQ_Module_V2#1]
In case a user violates the rule(for my case if he refreshes the page), the test is stopped for that person. There must be some way for that user to restart the test if he wishes to do so.
Possible solutions:
1) The test should start from the beginning, OR
2) He should be able(or have a choice) to sign up again with the same id and start the test.

**Comment by archit-dwevedi** [comment]
Suppose In Case A User is Given a Test of 29 Minutes and Knows all the Questions of the Portal and then He Refreshes the Page then According to your Solution He Should Start from the Beginning and Now He Knows all the Question then He will Get a Total Time of 59 Minutes to Solve the Same Quiz
